version: '3'

services:
  app:
    container_name: dotnet-node-dev
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:sqldb

    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  sqldb:
    container_name: mssql-dev
    # Use the latest SQL Server 2019 image. For more info, see https://aka.ms/dev-containers-mssql.
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y

    # Add "forwardPorts": ["mssqldb:1433"] to **devcontainer.json** to forward MSSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mongodb:
    container_name: mongodb-dev    
    # Use the latest MongoDB image. For more info, see https://aka.ms/dev-containers-mongodb.
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: D3vP@55W0rd!
    volumes:
      - mongo_data:/data/db

    # Add "forwardPorts": ["mongodb:1433"] to **devcontainer.json** to forward MSSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mongo_data:
    driver: local